Feature: UpdateLoanTerms
  @javascript
  Scenario: update loan terms
    When I am at loan member dashboard
      Then I click "Loan Terms"
      And I should see "Loan Summary"
      Then I clear value in "Property Value"
        And I fill in "Property Value" with "$999,999"
      Then I clear value in "Loan Amount"
        And I fill in "Loan Amount" with "$888,888"
      Then I clear value in "Interest Rate (%)"
        And I fill in "Interest Rate (%)" with "3.4"
        And I select "7/1 ARM" from "Loan Type"
      Then I clear value in "Lender Credits / Discount Points"
        And I fill in "Lender Credits / Discount Points" with "$777,777"
      Then I clear value in "Lender Fees"
        And I fill in "Lender Fees" with "$666,666"
      Then I clear value in "Down Payment"
        And I fill in "Down Payment" with "$555,555"
      Then I clear value in "Total Cash to Close (est.)"
        And I fill in "Total Cash to Close (est.)" with "$444,444"
      Then I clear value in "Principal and Interest"
        And I fill in "Principal and Interest" with "$333,333"
      Then I clear value in "Homeowners Insurance"
        And I fill in "Homeowners Insurance" with "$222,222"
      Then I clear value in "Property Tax"
        And I fill in "Property Tax" with "$111,111"
      Then I clear value in "HOA Due"
        And I fill in "HOA Due" with "$99,999"
      Then I clear value in "Mortgage Insurance"
        And I fill in "Mortgage Insurance" with "$88,888"
      Then I click on the element "#submit-loan-terms"
        And I wait for 2 seconds
      Then I reload the page
        And I confirm the browser dialog
        And I should see "Loan Terms"
      Then I click "Loan Terms"
        And I should see "$999,999.00"
        And I should see "$888,888.00"
        And I should see "$777,777.00"
        And I should see "$666,666.00"
        And I should see "$555,555.00"
        And I should see "$444,444.00"
        And I should see "$333,333.00"
        And I should see "$222,222.00"
        And I should see "$111,111.00"
        And I should see "$99,999.00"
        And I should see "$88,888.00"
