Feature: DocumentsTabAtNewLoanPage
  @javascript
  Scenario: User updates his income detail
    When I am at loan management page
      And I should see "Documents"
      And I click "Documents" in the "#tabDocuments"
      And I should see "W2 - Most recent tax year"
      And I should see "W2 - Previous tax year"
      And I should see "Paystub - Most recent period"
      And I should see "Paystub - Previous period"
      And I should see "Federal tax return - Most recent year"
      And I should see "Federal tax return - Previous year"
      And I should see "Bank statement - Most recent month"
      And I should see "Bank statement - Previous month"
      Then I drag the file "spec/files/sample.pdf" to "first_bank_statement"
        And I wait for 2 seconds
        And I should see "sample.pdf"
      And I click "Borrower" in the "#tabBorrower"
        And I choose "true_first_borrower_self_employed"
        Then I click on "Save and Continue"
          And I should see "Personal tax return - Most recent year"
          And I should see "Personal tax return - Previous year"
          And I should see "Business tax return - Most recent year"
          And I should see "Business tax return - Previous year"
          And I should see "Bank statement - Most recent month"
          And I should see "Bank statement - Previous month"
      When I click "Borrower" in the "#tabBorrower"
      When I select "With a co-borrower" from "I am applying"
        And I should see "Please provide information about your co-borrower"
        And I fill in "secondary_borrower_first_name" with "Mark"
        And I fill in "secondary_borrower_last_name" with "John"
        And I fill in "secondary_borrower_dob" with "01/01/1991"
        And I fill in "secondary_borrower_ssn" with "333333333"
        And I fill in "secondary_borrower_phone" with "12222222222"
        And I fill in "secondary_borrower_email" with "co-borrower@gmail.com"
        And I fill in "secondary_borrower_years_in_school" with "9"
        And I fill in "secondary_borrower_current_address" with "Albuquerque, Albuquerque, NM 87106"
        And I choose "true_secondary_borrower_currently_own"
        And I fill in "secondary_borrower_years_in_current_address" with "5"
        And I choose "false_secondary_borrower_self_employed"
        And I select "Married" from "secondary_borrower_marital_status"
        And I fill in "secondary_borrower_dependent_count" with "1"
        And I fill in "secondary_borrower_dependent_ages" with "1"
        Then I click on "Save and Continue"
        And I wait for 20 seconds
      When I click "Documents" in the "#tabDocuments"
        And I should see "Do you and your co-borrower file taxes jointly?"
        When I choose "false_is_file_taxes_jointly"
          And I should see "Please upload the following documents for your co-borrower."
          And I should see "W2 - Most recent tax year"
          And I should see "W2 - Previous tax year"
          And I should see "Paystub - Most recent period"
          And I should see "Paystub - Previous period"
          And I should see "Federal tax return - Most recent year"
          And I should see "Federal tax return - Previous year"
          And I should see "Bank statement - Most recent month"
          And I should see "Bank statement - Previous month"
        When I choose "true_is_file_taxes_jointly"
          And I should see "W2 - Most recent tax year"
          And I should see "W2 - Previous tax year"
          And I should see "Paystub - Most recent period"
          And I should see "Paystub - Previous period"
          And I should see "Bank statement - Most recent month"
          And I should see "Bank statement - Previous month"
      When I click "Borrower" in the "#tabBorrower"
        And I choose "true_secondary_borrower_self_employed"
        Then I click on "Save and Continue"
        When I choose "false_is_file_taxes_jointly"
          And I should see "Personal tax return - Most recent year"
          And I should see "Personal tax return - Previous year"
          And I should see "Business tax return - Most recent year"
          And I should see "Business tax return - Previous year"
          And I should see "Bank statement - Most recent month"
          And I should see "Bank statement - Previous month"
        When I choose "true_is_file_taxes_jointly"
          And I should see "Business tax return - Most recent year"
          And I should see "Business tax return - Previous year"
          And I should see "Bank statement - Most recent month"
          And I should see "Bank statement - Previous month"
        Then I click on "Save and Continue"
          And I should see "Name of current employer"
