Feature: IncomeTabAtNewLoanPage
  @javascript
  Scenario: Borrower updates his income detail
    When I am at loan management page
      And I should see "Income"
      And I click "Income" in the "#tabIncome"
      Then I fill in "Name of current employer" with "Any Company"
      Then I clear value in "Job Title"
        And I fill in "Job Title" with "Software Engineer"
      Then I clear value in "Years at this employer"
        And I fill in "Years at this employer" with "12"
      Then I clear value in "Contact Name"
        And I fill in "Contact Name" with "Cuong Vu"
      Then I clear value in "Contact Phone Number"
        And I fill in "Contact Phone Number" with "0912345678"
      Then I clear value in "Base Income"
        And I fill in "Base Income" with "123454"
      Then I click link with div ".overtime .iconTrash"
        And I click link with div ".commission .iconTrash"
        And I click link with div ".bonus .iconTrash"
      Then I click on "Add other income"
        And I should see "Income Type"
        And I should see "Annual Gross Amount"
        And I select "Interest" from "Income Type"
        And I clear value in "Annual Gross Amount"
        And I fill in "Annual Gross Amount" with "9876"
      Then I click on "Save and Continue"
        And I should see "We’re now ready to get a real-time credit check to verify your credit score and review your credit history"
      And I click "Income" in the "#tabIncome"
        Then I should see content as "Software Engineer"
          And I should see content as "Cuong Vu"
          And I should see content as "0912345678"
          And I should see content as "$123,454"
      And I should see "Documents"

  @javascript
  Scenario: Borrower updates his income detail and has years of employer is less than 2
    When I am at loan management page
      And I should see "Income"
      And I click "Income" in the "#tabIncome"
      Then I clear value in "Job Title"
        And I fill in "Job Title" with "Software Engineer"
      Then I clear value in "Years at this employer"
        And I fill in "Years at this employer" with "1"
      Then I should see "Name of previous employer"
        And I fill in "previous_employer_name" with "Eximbank"
        And I should see "Monthly Income"
          Then I fill in "previous_monthly_income" with "3333"
        And I should see "Job Title"
          Then I fill in "previous_job_title" with "CEO"
        And I should see "Years at this employer"
          Then I fill in "previous_duration" with "123"
      Then I click on "Save and Continue"
        And I should see "We’re now ready to get a real-time credit check to verify your credit score and review your credit history"
      And I click "Income" in the "#tabIncome"
        Then I should see content as "Software Engineer"
          And I should see "Name of previous employer"
          And I should see content as "Eximbank"
          And I should see content as "$3,333"
          And I should see content as "CEO"
          And I should see content as "123"
      And I should see "Documents"

  @javascript
  Scenario: Borrower updates his co-borrower's income detail
    When I am at loan management page which has co-borrower
      And I click "Borrower" in the "#tabBorrower"
      Then I select "With a co-borrower" from "I am applying"
        And I should see "Please provide information about your co-borrower"
        And I click on "Save and Continue"
        And I should see "W2 - Most recent tax year"
      Then I click "Income" in the "#tabIncome"
        And I should see "Please provide income information of your co-borrower"
      Then I clear value in "secondary_current_employer_name"
        And I fill in "secondary_current_employer_name" with "VCB"
      Then I clear value in "secondary_current_full_text_address"
        And I fill in "secondary_current_full_text_address" with "227 Nguyen Van Cu, Q.5"
      Then I clear value in "secondary_current_job_title"
        And I fill in "secondary_current_job_title" with "Business Analyst"
      Then I clear value in "secondary_current_duration"
        And I fill in "secondary_current_duration" with "5"
      Then I clear value in "secondary_employer_contact_name"
        And I fill in "secondary_employer_contact_name" with "Mr. Constantine"
      Then I clear value in "secondary_employer_contact_number"
        And I fill in "secondary_employer_contact_number" with "9091234785"
      Then I clear value in "secondary_current_salary"
        And I fill in "secondary_current_salary" with "9999"
      Then I select "Weekly" from "secondary_pay_frequency"
        And I click on "Save and Continue"
        And I should see "We’re now ready to get a real-time credit check to verify your credit score and review your credit history"
      Then I click "Income" in the "#tabIncome"
        And I should see content as "VCB"
        And I should see content as "227 Nguyen Van Cu, Q.5"
        And I should see content as "Business Analyst"
        And I should see content as "Mr. Constantine"
        And I should see content as "(909) 123-4785"
        And I should see content as "$9,999"
