Feature: Referrals
  @javascript
  Scenario: click on referrals tab
    When I am at my loans page
      Then I click "Referrals"
        And I should see "Referrals Program"
        And I should see "Your Referrals"
        And I should see "Your Referral Link"
        And I should see "Invite by Email"
        And I fill in "invite-email-1" with "test1@example.com"
        And I fill in "invite-name-1" with "Test 1"
        And I fill in "invite-phone-1" with "090 769 1123"
        And I fill in "invite-email-2" with "test2@example.com"
        And I fill in "invite-name-2" with "Test 2"
        And I fill in "invite-phone-2" with "090 769 8322"
        And I fill in "invite-email-3" with "test3@example.com"
        And I fill in "invite-name-3" with "Test 3"
        And I fill in "invite-phone-3" with "090 769 3333"
        Then I click on "SEND INVITES"
          And the "invite-email-1" field should contain ""
          And the "invite-email-2" field should contain ""
          And the "invite-email-3" field should contain ""
          And the "invite-name-1" field should contain ""
          And the "invite-name-1" field should contain ""
          And the "invite-name-1" field should contain ""
          And the "invite-phone-1" field should contain ""
          And the "invite-phone-1" field should contain ""
          And the "invite-phone-1" field should contain ""
        And I fill in "invite-email-1" with "test1"
        And I fill in "invite-name-1" with "Test 1"
        And I fill in "invite-phone-1" with "090 769 1123"
        Then I click on "SEND INVITES"
          And the "invite-email-1" field should contain "test1"
          And the "invite-name-1" field should contain "Test 1"
          And the "invite-phone-1" field should contain "090 769 1123"